name: Run Third-Party Executable

on:
  push:
    branches:
      - master

jobs:
  run_executable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest checked-in files
      run: |
        # This command finds the latest checked-in files in the repository
        latest_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | paste -s -d ',')
        echo "LATEST_FILES=${latest_files}" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Run Third-Party Executable
      run: |
        # Use the latest checked-in files as a parameter for your executable
        # Replace 'your_executable.exe' with the actual name of your executable
        echo "Using files: $LATEST_FILES"
        ls -l ./bin/PrudleScan.exe
        chmod +x ./bin/PrudleScan.exe
        "./bin/PrudleScan.exe" -files "${LATEST_FILES}" -config "./config/PrudleConfig.xml" -output "./output"
