name: Run Third-Party Executable

on:
  push:
    branches:
      - main

jobs:
  run_executable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest checked-in file
      id: find_file
      run: |
        # This command finds the latest checked-in file in the repository
        latest_file=$(git log -1 --name-only --pretty=format:'' | grep -E '\.exe$' | head -n 1)
        echo "::set-output name=latest_file::$latest_file"

    - name: Run Third-Party Executable
      run: |
        # Use the latest checked-in file as a parameter for your executable
        # Replace 'your_executable.exe' with the actual name of your executable
        ./bin/PrudleScan.exe "${{ steps.find_file.outputs.latest_file }}"
