name: Run Third-Party Executable

on:
  push:
    branches:
      - master

jobs:
  run_executable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find latest checked-in file
      id: find_file
      run: |
        ls -l ./bin/PrudleScan.exe
        chmod +x ./bin/PrudleScan.exe
        # This command finds the latest checked-in file in the repository
        latest_file=$(git log -1 --name-only --pretty=format:'' | head -n 1)
        echo "LATEST_FILE=${latest_file}" >> $GITHUB_ENV

    - name: Run Third-Party Executable
      run: |
        # Use the latest checked-in file as a parameter for your executable
        "./bin/PrudleScan.exe" -file "${{ env.LATEST_FILE }}" -config "./config/PrudleConfig.xml" -output "./output"
