name: Run Third-Party Executable

on:
  push:
    branches:
      - master

jobs:
  run_executable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Third-Party Executable
      id: find_file
      run: |
        ls -l ./bin/PrudleScan.exe
        chmod +x ./bin/PrudleScan.exe
        # This command finds the latest checked-in file in the repository
        latest_file=$(git log -1 --name-only --pretty=format:'' | head -n 1)
        LATEST_FILE=${latest_file}
        echo "LATEST_FILE=${latest_file}"
        "./bin/PrudleScan.exe" -file "${LATEST_FILE}" -config "./config/PrudleConfig.xml" -output "./output"
