name: Run Third-Party Executable

on:
  push:
    branches:
      - master

jobs:
  run_executable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Third-Party Executable
      id: find_file
      run: |
        ls -l ./bin/PrudleScan.exe
        chmod +x ./bin/PrudleScan.exe
        # This command finds the latest checked-in file in the repository
        latest_files=$(git log -1 --name-only --pretty=format:'' | grep -E '\.exe$' | tr '\n' ',' | sed 's/,$//')
        echo "::set-output name=latest_files::$latest_files"        
        "./bin/PrudleScan.exe" -files "${{ steps.find_files.outputs.latest_files }}" -config "./config/PrudleConfig.xml" -output "./output"
